"""Expose canonical score acceptance contracts."""

from perfcho.modules.scoring.errors import (
    AttemptIdempotencyConflict,
    BeatmapRevisionNotFound,
    MultiplayerContextRejected,
    ReplayNotFound,
    ScoreboardUnavailable,
    ScoreRejected,
)
from perfcho.modules.scoring.models import (
    AcceptedScoreResult,
    AcceptScore,
    AnticheatAnalysisRequested,
    BeatmapReference,
    CanonicalMod,
    ClientFamily,
    HitStatistic,
    LeaderboardPage,
    LeaderboardScoreView,
    MultiplayerSubmissionContext,
    PlayAttemptSubmission,
    ReplayReference,
    Ruleset,
    ScoreAttestation,
    ScoreboardVariant,
    ScoreGrade,
    ScoreOutcome,
    ScoreSubmission,
    StagedReplayManifest,
)
from perfcho.modules.scoring.services import RankingQueryService, ReplayQueryService, ReplayService, ScoringService

__all__ = (
    "AcceptScore",
    "AcceptedScoreResult",
    "AnticheatAnalysisRequested",
    "AttemptIdempotencyConflict",
    "BeatmapReference",
    "BeatmapRevisionNotFound",
    "CanonicalMod",
    "ClientFamily",
    "HitStatistic",
    "LeaderboardPage",
    "LeaderboardScoreView",
    "MultiplayerContextRejected",
    "MultiplayerSubmissionContext",
    "PlayAttemptSubmission",
    "ReplayNotFound",
    "ReplayQueryService",
    "ReplayReference",
    "ReplayService",
    "RankingQueryService",
    "Ruleset",
    "ScoreAttestation",
    "ScoreGrade",
    "ScoreOutcome",
    "ScoreRejected",
    "ScoreSubmission",
    "ScoreboardUnavailable",
    "ScoreboardVariant",
    "ScoringService",
    "StagedReplayManifest",
)
