"""Expose protocol-neutral multiplayer commands, values, ports, and services."""

from .commands import (
    MultiplayerCommandDependencies,
    build_multiplayer_commands,
    build_pool_commands,
)
from .errors import (
    MatchAlreadyJoined,
    MatchConcurrencyConflict,
    MatchFull,
    MatchNotFound,
    MatchPasswordRejected,
    MatchPermissionDenied,
    MatchProjectionUnavailable,
    MatchStateRejected,
    MultiplayerError,
)
from .models import (
    ChangeHost,
    ChangeRoomPassword,
    CleanupPresence,
    CompleteRound,
    CreateRoom,
    DurableRoomSnapshot,
    JoinRoom,
    KickParticipant,
    LeaveRoom,
    ProjectionStatus,
    RoomRecord,
    RoomSettings,
    RoomSlot,
    RoomState,
    RoundParticipantSelection,
    SlotStatus,
    StartRound,
    TeamMode,
    UpdateRoomSettings,
    WinCondition,
)
from .ports import MultiplayerAccessPolicy, MultiplayerRepository, MultiplayerStateRepository
from .services import MultiplayerService

__all__ = [
    "ChangeHost",
    "ChangeRoomPassword",
    "CleanupPresence",
    "CompleteRound",
    "CreateRoom",
    "DurableRoomSnapshot",
    "JoinRoom",
    "KickParticipant",
    "LeaveRoom",
    "MatchAlreadyJoined",
    "MatchConcurrencyConflict",
    "MatchFull",
    "MatchNotFound",
    "MatchPasswordRejected",
    "MatchPermissionDenied",
    "MatchProjectionUnavailable",
    "MatchStateRejected",
    "MultiplayerError",
    "MultiplayerRepository",
    "MultiplayerAccessPolicy",
    "MultiplayerCommandDependencies",
    "MultiplayerService",
    "MultiplayerStateRepository",
    "RoomRecord",
    "RoundParticipantSelection",
    "RoomSettings",
    "RoomSlot",
    "RoomState",
    "ProjectionStatus",
    "SlotStatus",
    "StartRound",
    "TeamMode",
    "UpdateRoomSettings",
    "WinCondition",
    "build_multiplayer_commands",
    "build_pool_commands",
]
