"""Expose the protocol-neutral application kernel."""

from perfcho.modules.common.errors import (
    AccountUnavailable,
    ApplicationError,
    AuthenticationFailed,
    AuthorizationDenied,
    ConcurrentModification,
    DependencyUnavailable,
    IdempotencyConflict,
    InputRejected,
    ObjectUnavailable,
    ProjectionUnavailable,
    RateLimitExceeded,
    ResourceConflict,
    ResourceNotFound,
    SessionExpired,
    SessionRevoked,
)
from perfcho.modules.common.models import Actor, ClientContext, CommandMeta, JsonValue, PendingEvent, StoredObject
from perfcho.modules.common.ports import (
    Clock,
    IdGenerator,
    ObjectStorage,
    ObjectStream,
    ObjectUrlProvider,
    OutboxWriter,
    OutboxWriterFactory,
    UnitOfWork,
    UnitOfWorkFactory,
)

__all__ = (
    "AccountUnavailable",
    "Actor",
    "ApplicationError",
    "AuthenticationFailed",
    "AuthorizationDenied",
    "ClientContext",
    "Clock",
    "CommandMeta",
    "ConcurrentModification",
    "DependencyUnavailable",
    "IdGenerator",
    "IdempotencyConflict",
    "InputRejected",
    "JsonValue",
    "ObjectUnavailable",
    "ObjectStorage",
    "ObjectStream",
    "ObjectUrlProvider",
    "OutboxWriter",
    "OutboxWriterFactory",
    "PendingEvent",
    "ProjectionUnavailable",
    "RateLimitExceeded",
    "ResourceConflict",
    "ResourceNotFound",
    "SessionExpired",
    "SessionRevoked",
    "StoredObject",
    "UnitOfWork",
    "UnitOfWorkFactory",
)
